apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-j33w
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tzvg-tenant/rhtap-demo-app/hacbs-test-project-j33w@sha256:24d231cd7bdf15803ed79341ba71a00ff5182535c1de2357d48fc4c3fc022168
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
