apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-j33w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-j33w
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-j33w
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-j33w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-j33w
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tzvg-tenant/rhtap-demo-app/hacbs-test-project-j33w@sha256:24d231cd7bdf15803ed79341ba71a00ff5182535c1de2357d48fc4c3fc022168
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
